projects:
  myportfolio:
    schemaPath: amplify/backend/api/myportfolio/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: eu-west-2
        apiId: null
        maxDepth: 2
